// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

type Command struct {
	ID              string `json:"id"`
	Aliased         string `json:"aliased"`
	ExpandedPreview string `json:"expanded_preview"`
	ExpandedFull    string `json:"expanded_full"`
	StartTs         string `json:"start_ts"`
	EndTs           string `json:"end_ts"`
	PeerIp          string `json:"peer_ip"`
	TmuxSession     string `json:"tmux_session"`
	TmuxWindow      string `json:"tmux_window"`
	TmuxPane        string `json:"tmux_pane"`
}
